version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PRODUCTION=False
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "5001:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./webapp/static:/app/webapp/static
    depends_on:
      - web
